###this is a test file by xuxw(xuxw76@yahoo.com)
import Magnus
a=Magnus.ACConfig( )
x=a.populationSize()  
x=a.numOfGenerations()  
x=a.haveFitnessScaling()  
x=a.useSumFitness()  
x=a.chanceOfCrossover( )  
x=a.chanceOfMutation( )  
x=a.numOfElitistSelection( )  
x=a.penaltyRate()  
x=a.crossoverType()  
x=a.chanceOfMutationAppend( )  
x=a.chanceOfMutationInsert( )  
x=a.chanceOfMutationDelete( )  
x=a.chanceOfMutationChange( )  
x=a.chanceOfMutationPermute()  
x=a.numMinmizeAfterOf()  
x=a.useWhitehead()  
print a
b=Magnus.ACConfigFromString("dsgfd")

