###this is a test file by xuxw(xuxw76@yahoo.com)
###cann't test because no permission to /peterHOME directory 
import Magnus
w1=Magnus.Word()
w2=Magnus.Word()
wo=Magnus.WordOrder()
g1=Magnus.Generator(3)
a=Magnus.RKBPackage(["dg","fh"], [w1,w2]) 
b=Magnus.RKBPackageFromWordOrder(["dg","fh"], [w1,w2],wo) 
b.getName()
b.runKB(1,1,1,1)
b.growthRate(1,1,1)
##float* growthRate(int maxLen, int numTrials, int seed);
b.saveToFiles()
b.printRules()
b.readRule("dsgdfhh", w1,w2)
b.oneOffRewrite(w1)
b.enterRewriteMode()
b.quitRewriteMode()
b.rewrite(w1)
b.wordDifferences()
b.differenceMachineFromSet([w1,w2])
b.differenceMachine()
b.KnuthBendixMachine()
b.getGeneratorNames()
b.rulesFilename()
b.currentNumOfRules()
b.isProvedConfluent()
b.rulesReduced(w1,w2,1)
b.sanityCheck()
b.getGeneratorName(g1)
