IN=${SRC}/backend/SessionManager/include
OUT=${INT}/include
DOC=${MNT}/${SYS}/doc/src/backend/SessionManager/include


FILES= ${OUT}/AlgebraicObject.h ${OUT}/ARCer.h \
       ${OUT}/ARC.h ${OUT}/ARCSlotID.h \
       ${OUT}/BaseProperties.h \
       ${OUT}/GCM.h ${OUT}/GIC.h \
       ${OUT}/InformationCenter.h ${OUT}/Menu.h \
       ${OUT}/MIC.h ${OUT}/ObjectFactory.h \
       ${OUT}/OID.h \
       ${OUT}/Property.h \
       ${OUT}/RandomDefinitionsGenerator.h ${OUT}/ResourceManager.h \
       ${OUT}/SMDataSet.h \
       ${OUT}/SMEqSystem.h \
       ${OUT}/SMEquation.h ${OUT}/SMFPGroup.h \
       ${OUT}/SMHomomorphism.h \
       ${OUT}/SMObject.h \
       ${OUT}/SMPermutation.h ${OUT}/SMPolynomial.h \
       ${OUT}/SMSetOfWords.h ${OUT}/SMSubgroup.h \
       ${OUT}/SMVectorOfWords.h ${OUT}/SMWord.h \
       ${OUT}/Supervisor.h \
       ${OUT}/ViewContents.h ${OUT}/viewStructure.h

DOCFILES= ${DOC}/AlgebraicObject.h.dvi ${DOC}/ARCer.h.dvi \
          ${DOC}/ARC.h.dvi ${DOC}/ARCSlotID.h.dvi \
          ${DOC}/BaseProperties.h.dvi \
          ${DOC}/GCM.h.dvi ${DOC}/GIC.h.dvi \
          ${DOC}/InformationCenter.h.dvi ${DOC}/Menu.h.dvi \
          ${DOC}/MIC.h.dvi ${DOC}/ObjectFactory.h.dvi \
          ${DOC}/OID.h.dvi \
          ${DOC}/Property.h.dvi \
          ${DOC}/RandomDefinitionsGenerator.h.dvi \
          ${DOC}/ResourceManager.h.dvi \
          ${DOC}/SMDataSet.h.dvi \
          ${DOC}/SMEqSystem.h.dvi \
          ${DOC}/SMEquation.h.dvi ${DOC}/SMFPGroup.h.dvi \
          ${DOC}/SMHomomorphism.h.dvi \
          ${DOC}/SMObject.h.dvi \
          ${DOC}/SMPermutation.h.dvi ${DOC}/SMPolynomial.h.dvi \
          ${DOC}/SMSetOfWords.h.dvi ${DOC}/SMSubgroup.h.dvi \
          ${DOC}/SMVectorOfWords.h.dvi ${DOC}/SMWord.h.dvi \
          ${DOC}/Supervisor.h.dvi \
          ${DOC}/ViewContents.h.dvi ${DOC}/viewStructure.h.dvi

all: ${FILES} ${DOCFILES}
	@echo 82 finished ${IN}

${OUT}/AlgebraicObject.h: ${IN}/AlgebraicObject.h.pamphlet
	@echo 1 making ${OUT}/AlgebraicObject.h from ${IN}/AlgebraicObject.h.pamphlet
	@${DOCUMENT} src AlgebraicObject.h ${OUT}

${DOC}/AlgebraicObject.h.dvi: ${IN}/AlgebraicObject.h.pamphlet ${DOC}/axiom.sty
	@echo 2 making ${DOC}/AlgebraicObject.h.dvi from ${IN}/AlgebraicObject.h.pamphlet 
	@${DOCUMENT} dvi AlgebraicObject.h ${DOC} AlgebraicObject.h ${NOISE}


${OUT}/ARCer.h: ${IN}/ARCer.h.pamphlet
	@echo 3 making ${OUT}/ARCer.h from ${IN}/ARCer.h.pamphlet
	@${DOCUMENT} src ARCer.h ${OUT}

${DOC}/ARCer.h.dvi: ${IN}/ARCer.h.pamphlet ${DOC}/axiom.sty
	@echo 4 making ${DOC}/ARCer.h.dvi from ${IN}/ARCer.h.pamphlet 
	@${DOCUMENT} dvi ARCer.h ${DOC} ARCer.h ${NOISE}


${OUT}/ARC.h: ${IN}/ARC.h.pamphlet
	@echo 5 making ${OUT}/ARC.h from ${IN}/ARC.h.pamphlet
	@${DOCUMENT} src ARC.h ${OUT}

${DOC}/ARC.h.dvi: ${IN}/ARC.h.pamphlet ${DOC}/axiom.sty
	@echo 6 making ${DOC}/ARC.h.dvi from ${IN}/ARC.h.pamphlet 
	@${DOCUMENT} dvi ARC.h ${DOC} ARC.h ${NOISE}


${OUT}/ARCSlotID.h: ${IN}/ARCSlotID.h.pamphlet
	@echo 7 making ${OUT}/ARCSlotID.h from ${IN}/ARCSlotID.h.pamphlet
	@${DOCUMENT} src ARCSlotID.h ${OUT}

${DOC}/ARCSlotID.h.dvi: ${IN}/ARCSlotID.h.pamphlet ${DOC}/axiom.sty
	@echo 8 making ${DOC}/ARCSlotID.h.dvi from ${IN}/ARCSlotID.h.pamphlet 
	@${DOCUMENT} dvi ARCSlotID.h ${DOC} ARCSlotID.h ${NOISE}


${OUT}/BaseProperties.h: ${IN}/BaseProperties.h.pamphlet
	@echo 9 making ${OUT}/BaseProperties.h from ${IN}/BaseProperties.h.pamphlet
	@${DOCUMENT} src BaseProperties.h ${OUT}

${DOC}/BaseProperties.h.dvi: ${IN}/BaseProperties.h.pamphlet ${DOC}/axiom.sty
	@echo 10 making ${DOC}/BaseProperties.h.dvi from ${IN}/BaseProperties.h.pamphlet 
	@${DOCUMENT} dvi BaseProperties.h ${DOC} BaseProperties.h ${NOISE}


${OUT}/GCM.h: ${IN}/GCM.h.pamphlet
	@echo 17 making ${OUT}/GCM.h from ${IN}/GCM.h.pamphlet
	@${DOCUMENT} src GCM.h ${OUT}

${DOC}/GCM.h.dvi: ${IN}/GCM.h.pamphlet ${DOC}/axiom.sty
	@echo 18 making ${DOC}/GCM.h.dvi from ${IN}/GCM.h.pamphlet 
	@${DOCUMENT} dvi GCM.h ${DOC} GCM.h ${NOISE}


${OUT}/GIC.h: ${IN}/GIC.h.pamphlet
	@echo 19 making ${OUT}/GIC.h from ${IN}/GIC.h.pamphlet
	@${DOCUMENT} src GIC.h ${OUT}

${DOC}/GIC.h.dvi: ${IN}/GIC.h.pamphlet ${DOC}/axiom.sty
	@echo 20 making ${DOC}/GIC.h.dvi from ${IN}/GIC.h.pamphlet 
	@${DOCUMENT} dvi GIC.h ${DOC} GIC.h ${NOISE}


${OUT}/InformationCenter.h: ${IN}/InformationCenter.h.pamphlet
	@echo 21 making ${OUT}/InformationCenter.h from ${IN}/InformationCenter.h.pamphlet
	@${DOCUMENT} src InformationCenter.h ${OUT}

${DOC}/InformationCenter.h.dvi: ${IN}/InformationCenter.h.pamphlet ${DOC}/axiom.sty
	@echo 22 making ${DOC}/InformationCenter.h.dvi from ${IN}/InformationCenter.h.pamphlet 
	@${DOCUMENT} dvi InformationCenter.h ${DOC} InformationCenter.h ${NOISE}


${OUT}/Menu.h: ${IN}/Menu.h.pamphlet
	@echo 23 making ${OUT}/Menu.h from ${IN}/Menu.h.pamphlet
	@${DOCUMENT} src Menu.h ${OUT}

${DOC}/Menu.h.dvi: ${IN}/Menu.h.pamphlet ${DOC}/axiom.sty
	@echo 24 making ${DOC}/Menu.h.dvi from ${IN}/Menu.h.pamphlet 
	@${DOCUMENT} dvi Menu.h ${DOC} Menu.h ${NOISE}


${OUT}/MIC.h: ${IN}/MIC.h.pamphlet
	@echo 25 making ${OUT}/MIC.h from ${IN}/MIC.h.pamphlet
	@${DOCUMENT} src MIC.h ${OUT}

${DOC}/MIC.h.dvi: ${IN}/MIC.h.pamphlet ${DOC}/axiom.sty
	@echo 26 making ${DOC}/MIC.h.dvi from ${IN}/MIC.h.pamphlet 
	@${DOCUMENT} dvi MIC.h ${DOC} MIC.h ${NOISE}


${OUT}/ObjectFactory.h: ${IN}/ObjectFactory.h.pamphlet
	@echo 27 making ${OUT}/ObjectFactory.h from ${IN}/ObjectFactory.h.pamphlet
	@${DOCUMENT} src ObjectFactory.h ${OUT}

${DOC}/ObjectFactory.h.dvi: ${IN}/ObjectFactory.h.pamphlet ${DOC}/axiom.sty
	@echo 28 making ${DOC}/ObjectFactory.h.dvi from ${IN}/ObjectFactory.h.pamphlet 
	@${DOCUMENT} dvi ObjectFactory.h ${DOC} ObjectFactory.h ${NOISE}


${OUT}/OID.h: ${IN}/OID.h.pamphlet
	@echo 31 making ${OUT}/OID.h from ${IN}/OID.h.pamphlet
	@${DOCUMENT} src OID.h ${OUT}

${DOC}/OID.h.dvi: ${IN}/OID.h.pamphlet ${DOC}/axiom.sty
	@echo 32 making ${DOC}/OID.h.dvi from ${IN}/OID.h.pamphlet 
	@${DOCUMENT} dvi OID.h ${DOC} OID.h ${NOISE}


${OUT}/Property.h: ${IN}/Property.h.pamphlet
	@echo 35 making ${OUT}/Property.h from ${IN}/Property.h.pamphlet
	@${DOCUMENT} src Property.h ${OUT}

${DOC}/Property.h.dvi: ${IN}/Property.h.pamphlet ${DOC}/axiom.sty
	@echo 36 making ${DOC}/Property.h.dvi from ${IN}/Property.h.pamphlet 
	@${DOCUMENT} dvi Property.h ${DOC} Property.h ${NOISE}


${OUT}/RandomDefinitionsGenerator.h: ${IN}/RandomDefinitionsGenerator.h.pamphlet
	@echo 37 making ${OUT}/RandomDefinitionsGenerator.h from ${IN}/RandomDefinitionsGenerator.h.pamphlet
	@${DOCUMENT} src RandomDefinitionsGenerator.h ${OUT}

${DOC}/RandomDefinitionsGenerator.h.dvi: ${IN}/RandomDefinitionsGenerator.h.pamphlet ${DOC}/axiom.sty
	@echo 38 making ${DOC}/RandomDefinitionsGenerator.h.dvi from ${IN}/RandomDefinitionsGenerator.h.pamphlet 
	@${DOCUMENT} dvi RandomDefinitionsGenerator.h ${DOC} RandomDefinitionsGenerator.h ${NOISE}


${OUT}/ResourceManager.h: ${IN}/ResourceManager.h.pamphlet
	@echo 39 making ${OUT}/ResourceManager.h from ${IN}/ResourceManager.h.pamphlet
	@${DOCUMENT} src ResourceManager.h ${OUT}

${DOC}/ResourceManager.h.dvi: ${IN}/ResourceManager.h.pamphlet ${DOC}/axiom.sty
	@echo 40 making ${DOC}/ResourceManager.h.dvi from ${IN}/ResourceManager.h.pamphlet 
	@${DOCUMENT} dvi ResourceManager.h ${DOC} ResourceManager.h ${NOISE}


${OUT}/SMDataSet.h: ${IN}/SMDataSet.h.pamphlet
	@echo 43 making ${OUT}/SMDataSet.h from ${IN}/SMDataSet.h.pamphlet
	@${DOCUMENT} src SMDataSet.h ${OUT}

${DOC}/SMDataSet.h.dvi: ${IN}/SMDataSet.h.pamphlet ${DOC}/axiom.sty
	@echo 44 making ${DOC}/SMDataSet.h.dvi from ${IN}/SMDataSet.h.pamphlet 
	@${DOCUMENT} dvi SMDataSet.h ${DOC} SMDataSet.h ${NOISE}


${OUT}/SMEqSystem.h: ${IN}/SMEqSystem.h.pamphlet
	@echo 47 making ${OUT}/SMEqSystem.h from ${IN}/SMEqSystem.h.pamphlet
	@${DOCUMENT} src SMEqSystem.h ${OUT}

${DOC}/SMEqSystem.h.dvi: ${IN}/SMEqSystem.h.pamphlet ${DOC}/axiom.sty
	@echo 48 making ${DOC}/SMEqSystem.h.dvi from ${IN}/SMEqSystem.h.pamphlet 
	@${DOCUMENT} dvi SMEqSystem.h ${DOC} SMEqSystem.h ${NOISE}


${OUT}/SMEquation.h: ${IN}/SMEquation.h.pamphlet
	@echo 49 making ${OUT}/SMEquation.h from ${IN}/SMEquation.h.pamphlet
	@${DOCUMENT} src SMEquation.h ${OUT}

${DOC}/SMEquation.h.dvi: ${IN}/SMEquation.h.pamphlet ${DOC}/axiom.sty
	@echo 50 making ${DOC}/SMEquation.h.dvi from ${IN}/SMEquation.h.pamphlet 
	@${DOCUMENT} dvi SMEquation.h ${DOC} SMEquation.h ${NOISE}


${OUT}/SMFPGroup.h: ${IN}/SMFPGroup.h.pamphlet
	@echo 51 making ${OUT}/SMFPGroup.h from ${IN}/SMFPGroup.h.pamphlet
	@${DOCUMENT} src SMFPGroup.h ${OUT}

${DOC}/SMFPGroup.h.dvi: ${IN}/SMFPGroup.h.pamphlet ${DOC}/axiom.sty
	@echo 52 making ${DOC}/SMFPGroup.h.dvi from ${IN}/SMFPGroup.h.pamphlet 
	@${DOCUMENT} dvi SMFPGroup.h ${DOC} SMFPGroup.h ${NOISE}


${OUT}/SMHomomorphism.h: ${IN}/SMHomomorphism.h.pamphlet
	@echo 53 making ${OUT}/SMHomomorphism.h from ${IN}/SMHomomorphism.h.pamphlet
	@${DOCUMENT} src SMHomomorphism.h ${OUT}

${DOC}/SMHomomorphism.h.dvi: ${IN}/SMHomomorphism.h.pamphlet ${DOC}/axiom.sty
	@echo 54 making ${DOC}/SMHomomorphism.h.dvi from ${IN}/SMHomomorphism.h.pamphlet 
	@${DOCUMENT} dvi SMHomomorphism.h ${DOC} SMHomomorphism.h ${NOISE}


${OUT}/SMObject.h: ${IN}/SMObject.h.pamphlet
	@echo 59 making ${OUT}/SMObject.h from ${IN}/SMObject.h.pamphlet
	@${DOCUMENT} src SMObject.h ${OUT}

${DOC}/SMObject.h.dvi: ${IN}/SMObject.h.pamphlet ${DOC}/axiom.sty
	@echo 60 making ${DOC}/SMObject.h.dvi from ${IN}/SMObject.h.pamphlet 
	@${DOCUMENT} dvi SMObject.h ${DOC} SMObject.h ${NOISE}


${OUT}/SMPermutation.h: ${IN}/SMPermutation.h.pamphlet
	@echo 61 making ${OUT}/SMPermutation.h from ${IN}/SMPermutation.h.pamphlet
	@${DOCUMENT} src SMPermutation.h ${OUT}

${DOC}/SMPermutation.h.dvi: ${IN}/SMPermutation.h.pamphlet ${DOC}/axiom.sty
	@echo 62 making ${DOC}/SMPermutation.h.dvi from ${IN}/SMPermutation.h.pamphlet 
	@${DOCUMENT} dvi SMPermutation.h ${DOC} SMPermutation.h ${NOISE}


${OUT}/SMPolynomial.h: ${IN}/SMPolynomial.h.pamphlet
	@echo 63 making ${OUT}/SMPolynomial.h from ${IN}/SMPolynomial.h.pamphlet
	@${DOCUMENT} src SMPolynomial.h ${OUT}

${DOC}/SMPolynomial.h.dvi: ${IN}/SMPolynomial.h.pamphlet ${DOC}/axiom.sty
	@echo 64 making ${DOC}/SMPolynomial.h.dvi from ${IN}/SMPolynomial.h.pamphlet 
	@${DOCUMENT} dvi SMPolynomial.h ${DOC} SMPolynomial.h ${NOISE}


${OUT}/SMSetOfWords.h: ${IN}/SMSetOfWords.h.pamphlet
	@echo 65 making ${OUT}/SMSetOfWords.h from ${IN}/SMSetOfWords.h.pamphlet
	@${DOCUMENT} src SMSetOfWords.h ${OUT}

${DOC}/SMSetOfWords.h.dvi: ${IN}/SMSetOfWords.h.pamphlet ${DOC}/axiom.sty
	@echo 66 making ${DOC}/SMSetOfWords.h.dvi from ${IN}/SMSetOfWords.h.pamphlet 
	@${DOCUMENT} dvi SMSetOfWords.h ${DOC} SMSetOfWords.h ${NOISE}


${OUT}/SMSubgroup.h: ${IN}/SMSubgroup.h.pamphlet
	@echo 67 making ${OUT}/SMSubgroup.h from ${IN}/SMSubgroup.h.pamphlet
	@${DOCUMENT} src SMSubgroup.h ${OUT}

${DOC}/SMSubgroup.h.dvi: ${IN}/SMSubgroup.h.pamphlet ${DOC}/axiom.sty
	@echo 68 making ${DOC}/SMSubgroup.h.dvi from ${IN}/SMSubgroup.h.pamphlet 
	@${DOCUMENT} dvi SMSubgroup.h ${DOC} SMSubgroup.h ${NOISE}


${OUT}/SMVectorOfWords.h: ${IN}/SMVectorOfWords.h.pamphlet
	@echo 69 making ${OUT}/SMVectorOfWords.h from ${IN}/SMVectorOfWords.h.pamphlet
	@${DOCUMENT} src SMVectorOfWords.h ${OUT}

${DOC}/SMVectorOfWords.h.dvi: ${IN}/SMVectorOfWords.h.pamphlet ${DOC}/axiom.sty
	@echo 70 making ${DOC}/SMVectorOfWords.h.dvi from ${IN}/SMVectorOfWords.h.pamphlet 
	@${DOCUMENT} dvi SMVectorOfWords.h ${DOC} SMVectorOfWords.h ${NOISE}


${OUT}/SMWord.h: ${IN}/SMWord.h.pamphlet
	@echo 71 making ${OUT}/SMWord.h from ${IN}/SMWord.h.pamphlet
	@${DOCUMENT} src SMWord.h ${OUT}

${DOC}/SMWord.h.dvi: ${IN}/SMWord.h.pamphlet ${DOC}/axiom.sty
	@echo 72 making ${DOC}/SMWord.h.dvi from ${IN}/SMWord.h.pamphlet 
	@${DOCUMENT} dvi SMWord.h ${DOC} SMWord.h ${NOISE}


${OUT}/Supervisor.h: ${IN}/Supervisor.h.pamphlet
	@echo 73 making ${OUT}/Supervisor.h from ${IN}/Supervisor.h.pamphlet
	@${DOCUMENT} src Supervisor.h ${OUT}

${DOC}/Supervisor.h.dvi: ${IN}/Supervisor.h.pamphlet ${DOC}/axiom.sty
	@echo 74 making ${DOC}/Supervisor.h.dvi from ${IN}/Supervisor.h.pamphlet 
	@${DOCUMENT} dvi Supervisor.h ${DOC} Supervisor.h ${NOISE}


${OUT}/ViewContents.h: ${IN}/ViewContents.h.pamphlet
	@echo 77 making ${OUT}/ViewContents.h from ${IN}/ViewContents.h.pamphlet
	@${DOCUMENT} src ViewContents.h ${OUT}

${DOC}/ViewContents.h.dvi: ${IN}/ViewContents.h.pamphlet ${DOC}/axiom.sty
	@echo 78 making ${DOC}/ViewContents.h.dvi from ${IN}/ViewContents.h.pamphlet 
	@${DOCUMENT} dvi ViewContents.h ${DOC} ViewContents.h ${NOISE}


${OUT}/viewStructure.h: ${IN}/viewStructure.h.pamphlet
	@echo 79 making ${OUT}/viewStructure.h from ${IN}/viewStructure.h.pamphlet
	@${DOCUMENT} src viewStructure.h ${OUT}

${DOC}/viewStructure.h.dvi: ${IN}/viewStructure.h.pamphlet ${DOC}/axiom.sty
	@echo 80 making ${DOC}/viewStructure.h.dvi from ${IN}/viewStructure.h.pamphlet 
	@${DOCUMENT} dvi viewStructure.h ${DOC} viewStructure.h ${NOISE}


${DOC}/axiom.sty: ${SRC}/doc/axiom.sty.pamphlet
	@ echo 81 making ${DOC}/axiom.sty from ${SRC}/doc/axiom.sty.pamphlet
	@${DOCUMENT} chunk "axiom.sty" ${SRC}/doc/axiom.sty ${DOC} axiom.sty
 
