IN=${SRC}/backend/Subgroup/include
OUT=${INT}/include
DOC=${MNT}/${SYS}/doc/src/backend/Subgroup/include


FILES= ${OUT}/DecomposeInSubgroup.h ${OUT}/DoubleCosetGraph.h \
       ${OUT}/GraphConjugacyProblem.h \
       ${OUT}/PresentationsOfSubgroup.h ${OUT}/SGofFreeGroup.h \
       ${OUT}/SubgroupGraph.h ${OUT}/SubgroupGraphRep.h \
       ${OUT}/Subgroup.h ${OUT}/TurnerProperSubgroupEnumerator.h

DOCFILES= ${DOC}/DecomposeInSubgroup.h.dvi ${DOC}/DoubleCosetGraph.h.dvi \
          ${DOC}/GraphConjugacyProblem.h.dvi \
          ${DOC}/PresentationsOfSubgroup.h.dvi ${DOC}/SGofFreeGroup.h.dvi \
          ${DOC}/SubgroupGraph.h.dvi ${DOC}/SubgroupGraphRep.h.dvi \
          ${DOC}/Subgroup.h.dvi ${DOC}/TurnerProperSubgroupEnumerator.h.dvi

all: ${FILES} ${DOCFILES}
	@echo 20 finished ${IN}

${OUT}/DecomposeInSubgroup.h: ${IN}/DecomposeInSubgroup.h.pamphlet
	@echo 1 making ${OUT}/DecomposeInSubgroup.h from ${IN}/DecomposeInSubgroup.h.pamphlet
	@${DOCUMENT} src DecomposeInSubgroup.h ${OUT}

${DOC}/DecomposeInSubgroup.h.dvi: ${IN}/DecomposeInSubgroup.h.pamphlet ${DOC}/axiom.sty
	@echo 2 making ${DOC}/DecomposeInSubgroup.h.dvi from ${IN}/DecomposeInSubgroup.h.pamphlet 
	@${DOCUMENT} dvi DecomposeInSubgroup.h ${DOC} DecomposeInSubgroup.h ${NOISE}


${OUT}/DoubleCosetGraph.h: ${IN}/DoubleCosetGraph.h.pamphlet
	@echo 3 making ${OUT}/DoubleCosetGraph.h from ${IN}/DoubleCosetGraph.h.pamphlet
	@${DOCUMENT} src DoubleCosetGraph.h ${OUT}

${DOC}/DoubleCosetGraph.h.dvi: ${IN}/DoubleCosetGraph.h.pamphlet ${DOC}/axiom.sty
	@echo 4 making ${DOC}/DoubleCosetGraph.h.dvi from ${IN}/DoubleCosetGraph.h.pamphlet 
	@${DOCUMENT} dvi DoubleCosetGraph.h ${DOC} DoubleCosetGraph.h ${NOISE}


${OUT}/GraphConjugacyProblem.h: ${IN}/GraphConjugacyProblem.h.pamphlet
	@echo 5 making ${OUT}/GraphConjugacyProblem.h from ${IN}/GraphConjugacyProblem.h.pamphlet
	@${DOCUMENT} src GraphConjugacyProblem.h ${OUT}

${DOC}/GraphConjugacyProblem.h.dvi: ${IN}/GraphConjugacyProblem.h.pamphlet ${DOC}/axiom.sty
	@echo 6 making ${DOC}/GraphConjugacyProblem.h.dvi from ${IN}/GraphConjugacyProblem.h.pamphlet 
	@${DOCUMENT} dvi GraphConjugacyProblem.h ${DOC} GraphConjugacyProblem.h ${NOISE}


${OUT}/PresentationsOfSubgroup.h: ${IN}/PresentationsOfSubgroup.h.pamphlet
	@echo 7 making ${OUT}/PresentationsOfSubgroup.h from ${IN}/PresentationsOfSubgroup.h.pamphlet
	@${DOCUMENT} src PresentationsOfSubgroup.h ${OUT}

${DOC}/PresentationsOfSubgroup.h.dvi: ${IN}/PresentationsOfSubgroup.h.pamphlet ${DOC}/axiom.sty
	@echo 8 making ${DOC}/PresentationsOfSubgroup.h.dvi from ${IN}/PresentationsOfSubgroup.h.pamphlet 
	@${DOCUMENT} dvi PresentationsOfSubgroup.h ${DOC} PresentationsOfSubgroup.h ${NOISE}


${OUT}/SGofFreeGroup.h: ${IN}/SGofFreeGroup.h.pamphlet
	@echo 9 making ${OUT}/SGofFreeGroup.h from ${IN}/SGofFreeGroup.h.pamphlet
	@${DOCUMENT} src SGofFreeGroup.h ${OUT}

${DOC}/SGofFreeGroup.h.dvi: ${IN}/SGofFreeGroup.h.pamphlet ${DOC}/axiom.sty
	@echo 10 making ${DOC}/SGofFreeGroup.h.dvi from ${IN}/SGofFreeGroup.h.pamphlet 
	@${DOCUMENT} dvi SGofFreeGroup.h ${DOC} SGofFreeGroup.h ${NOISE}


${OUT}/SubgroupGraph.h: ${IN}/SubgroupGraph.h.pamphlet
	@echo 11 making ${OUT}/SubgroupGraph.h from ${IN}/SubgroupGraph.h.pamphlet
	@${DOCUMENT} src SubgroupGraph.h ${OUT}

${DOC}/SubgroupGraph.h.dvi: ${IN}/SubgroupGraph.h.pamphlet ${DOC}/axiom.sty
	@echo 12 making ${DOC}/SubgroupGraph.h.dvi from ${IN}/SubgroupGraph.h.pamphlet 
	@${DOCUMENT} dvi SubgroupGraph.h ${DOC} SubgroupGraph.h ${NOISE}


${OUT}/SubgroupGraphRep.h: ${IN}/SubgroupGraphRep.h.pamphlet
	@echo 13 making ${OUT}/SubgroupGraphRep.h from ${IN}/SubgroupGraphRep.h.pamphlet
	@${DOCUMENT} src SubgroupGraphRep.h ${OUT}

${DOC}/SubgroupGraphRep.h.dvi: ${IN}/SubgroupGraphRep.h.pamphlet ${DOC}/axiom.sty
	@echo 14 making ${DOC}/SubgroupGraphRep.h.dvi from ${IN}/SubgroupGraphRep.h.pamphlet 
	@${DOCUMENT} dvi SubgroupGraphRep.h ${DOC} SubgroupGraphRep.h ${NOISE}


${OUT}/Subgroup.h: ${IN}/Subgroup.h.pamphlet
	@echo 15 making ${OUT}/Subgroup.h from ${IN}/Subgroup.h.pamphlet
	@${DOCUMENT} src Subgroup.h ${OUT}

${DOC}/Subgroup.h.dvi: ${IN}/Subgroup.h.pamphlet ${DOC}/axiom.sty
	@echo 16 making ${DOC}/Subgroup.h.dvi from ${IN}/Subgroup.h.pamphlet 
	@${DOCUMENT} dvi Subgroup.h ${DOC} Subgroup.h ${NOISE}


${OUT}/TurnerProperSubgroupEnumerator.h: ${IN}/TurnerProperSubgroupEnumerator.h.pamphlet
	@echo 17 making ${OUT}/TurnerProperSubgroupEnumerator.h from ${IN}/TurnerProperSubgroupEnumerator.h.pamphlet
	@${DOCUMENT} src TurnerProperSubgroupEnumerator.h ${OUT}

${DOC}/TurnerProperSubgroupEnumerator.h.dvi: ${IN}/TurnerProperSubgroupEnumerator.h.pamphlet ${DOC}/axiom.sty
	@echo 18 making ${DOC}/TurnerProperSubgroupEnumerator.h.dvi from ${IN}/TurnerProperSubgroupEnumerator.h.pamphlet 
	@${DOCUMENT} dvi TurnerProperSubgroupEnumerator.h ${DOC} TurnerProperSubgroupEnumerator.h ${NOISE}


${DOC}/axiom.sty: ${SRC}/doc/axiom.sty.pamphlet
	@ echo 19 making ${DOC}/axiom.sty from ${SRC}/doc/axiom.sty.pamphlet
	@${DOCUMENT} chunk "axiom.sty" ${SRC}/doc/axiom.sty ${DOC} axiom.sty
 
