###this is a test file by xuxw(xuxw76@yahoo.com)
import Magnus
w1=Magnus.Word()
w2=Magnus.Word()
ws=[w1,w2]
g1=Magnus.Generator(2)
g2=Magnus.Generator(3)
rg=Magnus.OneRelatorGroup( 1, w1)
####
a=Magnus.MagnusBreakdown( rg )
x=a.getORGroup() 
x=a.getHNNPresentation() 
x=a.numberOfUsedGenerators()  
x=a.stableGenerator()  
x=a.hasAccompGenerator()  
x=a.accompGenerator() 
x=a.getGeneratorsWithZeroExpSum()  
x=a.getGeneratorsWithNonzeroExpSum()  
x=a.getDefaultBreakdownGenerators() 
x=a.getExponentSumOf( g1 )  
x=a.rewriteWordInOldGenerators( w1)  
x=a.rewriteWordInNewGenerators( w1) 
x=a.embeddingOfORGroups( )  
x=a.toORGroup( )  
x=a.numberOfOldGenerators( )  
x=a.numberOfNewGenerators( )  
###VectorOf<Range> getSubscriptsTable()  
x=a.adjoinSubscript(g1,1) 
x=a.extractSubscript(g1, 1) 
x=a.hasHNNPresentation()  
x=a.findHNNPresentation()
x=a.findHNNPresentationFromGenerator(g1 )
x=a.findHNNPresentationFromGeneratorGenerator( g1, g2)
###undefined x=a.readFrom( istream& istr ) 
a.printOn() 
a.debugPrint()
