###this is a test file by xuxw(xuxw76@yahoo.com)
import Magnus
w1=Magnus.Word()
w2=Magnus.Word()
g=Magnus.FPGroup()
ag=Magnus.AbelianGroup( g)
a=Magnus.AbelianEquationsSolverFromGroup(ag , [w1,w2] ,3 )
b=Magnus.AbelianEquationsSolver( )
a.findSolutions( "dgdg")
x=a.getBasicSolutions() 
####VectorOf< VectorOf< VectorOf<int> > > getTorsionPart() 
####VectorOf< VectorOf< VectorOf<int> > > getParametrizedPart() 
x=a.getSystemRank() 
x=a.getNumberOfParams() 
x=a.solIsAllGroup( ) 
x=a.haveSolutions() 
