###this is a test file by xuxw(xuxw76@yahoo.com)
import Magnus
w1=Magnus.Word()
w2=Magnus.Word()
aw=Magnus.AbelianWord()
ws=[w1,w2]
g=Magnus.FPGroup()
a=Magnus.AbelianGroup( g)
ag=Magnus.AbelianGroup( g)
a.computeCyclicDecomposition( ) 
a.findPrimaryBasis() 
x=a.haveCyclicDecomposition( ) 
x=a.havePrimaryDecomposition( ) 
x=a.getFileName( ) 
x=a.getFileNameOfPDGens( ) 
x=a.getFPGroup( ) 
x=a.getAllRelators( ) 
x=a.oldInAbelianForm( w1 ) 
x=a.rankOfFreeAbelianFactor( ) 
x=a.invariants( ) 
x=a.oldToNewGens() 
x=a.newToOldGens() 
x=a.getCanonicalSmithPresentation( ) 
x=a.order() 
x=a.isTrivial() 
x=a.isFinite() 
x=a.isInfinite() 
x=a.isFree() 
x=a.isomorphicTo( ag) 
x=a.computeIntegralHomology( 2) 
x=a.orderOfTheTorsionSubgroup( ) 
x=a.makeSubgroupPresentation(ws) 
x=a.findSubgroupIsolator(ws) 
x=a.findVirtFreeComplementOfSG(ws) 
x=a.joinSubgroups(ws,ws) 
x=a.findSubgIntersection( ws ,ws ,"dgfdg") 
x=a.isPureCyclSubgroup(w1) 
x=a.areEqual(w1, w2) 
x=a.isTrivialFromWord( w1 ) 
x=a.orderOfElt( w1) 
x=a.newToOldGensFromAbelianWord( aw) 
x=a.oldToNewGensFromAbelianWord(aw ) 
x=a.findEltPrimeForm(w1) 
x=a.pBlockOfElt( aw,3)
x=a.pBlockOfEltFromWord( w1,3)
x=a.pHeightOfElt(w1, 2, 2)
x=a.powerOfEltInSubgroup(w1,ws) 
x=a.isEltProperPower(w1) 
a.abelianMaximalRoot(w1,w2, 3) 
x=a.primeFormInOldGens(aw) 
x=a.isPowerOfSecond(w1, w2) 
x=a.isEpimorphism(ws) 
x=a.orderOfAuto(ws) 
x=a.inverseAuto(ws) 
x=a.fixedPointsOfAuto( ws ) 
x=a.test(3);
print a
a.printWordInNewGens(aw)
a.printInPrimaryForm(aw)
a.printPrimaryDec() 
