###this is a test file by xuxw(xuxw76@yahoo.com)
import Magnus
a=Magnus.MSCGroup();
w1=Magnus.Word()
w2=Magnus.Word()
g=Magnus.FPGroup()
b=Magnus.MSCGroupFromSet( 2,[w1,w2])
c=Magnus.MSCGroupFromFPGroup( g) 
x=a.order() 
x=a.isTrivial() 
x=a.isFinite() 
x=a.isInfinite() 
x=a.isAbelian() 
x=a.isFree() 
x=a.getMSCLambda() 
x=a.shortenByRelators(w1) 
x=a.cyclicallyShortenByRelators(w1) 
x=a.eval( w1 ) 
x=a.wordProblem( w1 ) 
x=a.areEqual(w1,w2) 
