###this is a test file by xuxw(xuxw76@yahoo.com)
import Magnus
w1=Magnus.Word()
w2=Magnus.Word()
ws=[w1,w2]
t=Magnus.Timer(10)
fg=Magnus.FreeGroup(2)
g=Magnus.Generator(2)
fg=Magnus.FPGroup()
g1=Magnus.Group()
gg=Magnus.FGGroup(g1)
sg=Magnus.Subgroup( gg)
####
a=Magnus.DecomposeInSubgroupOfFreeGroup( 1, ws ) 
x=a.clone( ) 
x=a.rankOfFreeGroup( )  
x=a.generators( )  
x=a.graph() 
x=a.decomposeNielsenBasis( ) 
x=a.contains( w1 ) 
x=a.decompose( w1 ) 
x=a.checkDecomposition( w1 ) 
x=a.DecomposeInSubgroupOfFreeGroupFromSubgroupGraph( sg,ws ) 
####
a=DecomposeInExpandingSubgroup( 1,ws,ws) 
x=a.clone( )  
x=a.constantGenerators( )  
x=a.expandingGenerators( )  
x=a.expandingConjugators( )  
a.expandSubgroupByConjugation( g ) 
a.expressAsConjugateOfOriginalGenerator(g,g, w1)
x=a.fullDecomposition( w1 ) 
x=a.checkDecomposition( w1 ) 
x=a.readPiece( "sdf", t ) 
####Inherited From  DecomposeInSubgroupOfFreeGroup
x=a.clone( ) 
x=a.rankOfFreeGroup( )  
x=a.generators( )  
x=a.graph() 
x=a.decomposeNielsenBasis( ) 
x=a.contains( w1 ) 
x=a.decompose( w1 ) 
x=a.checkDecomposition( w1 ) 
x=a.DecomposeInSubgroupOfFreeGroupFromSubgroupGraph( sg,ws ) 
####
a=Magnus.DecomposeInSubgroupOfFPGroup( fg, ws ) 
x=a.clone( )  
x=a.group()  
a.expandGraph( ) 
x=a.numberOfIterations( )  
x=a.readPiece( "dsg", t) 
###Inherited From DecomposeInExpandingSubgroup
x=a.clone( )  
x=a.constantGenerators( )  
x=a.expandingGenerators( )  
x=a.expandingConjugators( )  
a.expandSubgroupByConjugation( g ) 
a.expressAsConjugateOfOriginalGenerator(g,g, w1)
x=a.fullDecomposition( w1 ) 
x=a.checkDecomposition( w1 ) 
x=a.readPiece( "sdf", t ) 
####Inherited From  DecomposeInSubgroupOfFreeGroup
x=a.clone( ) 
x=a.rankOfFreeGroup( )  
x=a.generators( )  
x=a.graph() 
x=a.decomposeNielsenBasis( ) 
x=a.contains( w1 ) 
x=a.decompose( w1 ) 
x=a.checkDecomposition( w1 ) 
x=a.DecomposeInSubgroupOfFreeGroupFromSubgroupGraph( sg,ws ) 

