###this is a test file by xuxw(xuxw76@yahoo.com)
##include enum problem
import Magnus
w1=Magnus.Word()
w2=Magnus.Word()
t=Magnus.Timer(10)
ws=[w1,w2]
g=Magnus.Generator(2)
####
a=Magnus.SubgroupGraph(1, ws) 
b=Magnus.SubgroupGraphFromVector(1, ws);
x=a.rank( )  
x=a.normalizer( ) 
x=a.nielsenBasis( )  
x=a.nielsenWord(1)  
x=a.inNielsenWords(w1)  
x=a.join(b)  
x=a.intersection(b)  
x=a.contains(w1)  
x=a.containsFromSet(ws)  
x=a.containsFromVector(ws)  
x=a.containsFromSubgroupGraph(b)  
x=a.equalTo(ws) 
x=a.equalToFromSubgroupGraph(b) 
x=a.conjugateInSubgroup(w1, w2)  
x=a.conjugateInSubgroupFromSet(ws, w1) 
x=a.conjugateTo(ws) 
x=a.powerInSubgroup( w1 )  
x=a.findIndex()
x=a.findWhiteheadBasis() 
x=a.isAFreeFactor() 
x=a.generatesTheFreeGroup()  
x=a.rightSchreierRepresentative(w1) 
x=a.MHallCompletion( )  
a.MHallComplete( ) 
a.joinConjugate(g) 
x=a.completeness( )  
x=a.isComplete( )  
x=a.vertexCount( )  
x=a.targetOfGenerator(1, 1)  
x=a.targetOfLabel(1, 1)  
x=a.getValence( )  
x=a.inverseLabel(1)  
x=a.labelToGenerator(1)  
x=a.generatorToLabel(1)  
x=a.readPiece("sdf",t)
