###this is a test file by xuxw(xuxw76@yahoo.com)
import Magnus
w=Magnus.Word()
pw=Magnus.PolyWord()
b=Magnus.NGCollector(1,1)
g=Magnus.Generator(3)
bc=Magnus.BasicCommutators(1, 1)
####
a=Magnus.CollectorToTheLeft(1,1)
b=Magnus.CollectorToTheLeftFromBasicCommutators(bc)
##Inherited from NilpotentCollector
a.initialize()
x=a.make(1,1,0)
x=a.clone()
x=a.commutators()  
x=a.type()
x=a.isInitialized()  
a.collectingProcess(  pw )  
x=a.collect( w)  
x=a.collectFromPolyWord( pw)  
x=a.collectLetter(pw, g)  
x=a.multiply(pw, pw)  
x=a.raiseToPower(pw, 2)  
x=a.inverse(pw)  
x=a.weightOf( w)  
x=a.weightOfFromPolyWord(pw)  
a.writeIPC()  
a.readIPC("dgfd")
###
c=magnus.CollectorFromTheLeft(1,2)
d=magnus.CollectorFromTheLeftFromBasicCommutators(bc)
##Inherited from NilpotentCollector
a.initialize()
x=a.make(1,1);
x=a.clone()
x=a.commutators()  
x=a.type()
x=a.isInitialized()  
a.collectingProcess(  pw )  
x=a.collect( w)  
x=a.collectFromPolyWord( pw)  
x=a.collectLetter(pw, g)  
x=a.multiply(pw, pw)  
x=a.raiseToPower(pw, 2)  
x=a.inverse(pw)  
x=a.weightOf( w)  
x=a.weightOfFromPolyWord(pw)  
a.writeIPC()  
a.readIPC("dgfd")
