###this is a test file by xuxw(xuxw76@yahoo.com)
import Magnus
w1=Magnus.Word()
w2=Magnus.Word()
pw1=Magnus.PolyWord()
pw2=Magnus.PolyWord()
g=Magnus.Generator(2)
l=Magnus.Letter()
a=Magnus.PolyWordIterator(pw1) 
####b=Magnus.PolyWordIteratorFromPolyWordRep(PolyWordRep* )  
a.startFromLeft() 
a.startFromRight() 
a.stepRight() 
a.stepLeft() 
x=a.done()  
x=a.searchToLeft( g) 
x=a.position() 
x=a.thisLetter()  
x=a.leftLetter()  
x=a.rightLetter()  
x=a.isFirst()  
x=a.isLast()  
x=a.collectToRight() 
a.splitToLeft() 
a.insertRight(pw1) 
a.insertLeft(pw1) 
a.insertRightFromLetter(l) 
a.insertLeftFromLetter(l) 
a.removeThisLetter() 
a.removeLeftLetter() 
a.removeRightLetter() 
a.decreaseLeftLetter() 
a.exchangeToLeft() 
