IN=${SRC}/backend/AProducts/include
OUT=${INT}/include
DOC=${MNT}/${SYS}/doc/src/backend/AProducts/include


FILES= ${OUT}/AmalgamatedProductParser.h ${OUT}/AP-fixups.h \
       ${OUT}/APofFreeGroups.h ${OUT}/APofFreeGroupsRep.h \
       ${OUT}/APwithOneRelator.h ${OUT}/APwithOneRelatorRep.h \
       ${OUT}/CONDITION.h \
       ${OUT}/HNNExtension.h ${OUT}/HNNExtOfFreeGroup.h \
       ${OUT}/HNNExtOfORGroup.h ${OUT}/HNNParser.h \
       ${OUT}/MagnusBreakdown.h ${OUT}/Margin.h \
       ${OUT}/OneRelatorGroup.h \
       ${OUT}/OneRelatorGroupWithTorsion.h ${OUT}/ORProblems.h \
       ${OUT}/Range.h ${OUT}/ShortenByRelators2.h \
       ${OUT}/SubgroupOfOneRelatorGroup.h ${OUT}/SuperGen.h \
       ${OUT}/Whitehead.h

DOCFILES= ${DOC}/AmalgamatedProductParser.h.dvi ${DOC}/AP-fixups.h.dvi \
          ${DOC}/APofFreeGroups.h.dvi ${DOC}/APofFreeGroupsRep.h.dvi \
          ${DOC}/APwithOneRelator.h.dvi ${DOC}/APwithOneRelatorRep.h.dvi \
          ${DOC}/CONDITION.h.dvi \
          ${DOC}/HNNExtension.h.dvi ${DOC}/HNNExtOfFreeGroup.h.dvi \
          ${DOC}/HNNExtOfORGroup.h.dvi ${DOC}/HNNParser.h.dvi \
          ${DOC}/MagnusBreakdown.h.dvi ${DOC}/Margin.h.dvi \
          ${DOC}/OneRelatorGroup.h.dvi \
          ${DOC}/OneRelatorGroupWithTorsion.h.dvi ${DOC}/ORProblems.h.dvi \
          ${DOC}/Range.h.dvi ${DOC}/ShortenByRelators2.h.dvi \
          ${DOC}/SubgroupOfOneRelatorGroup.h.dvi ${DOC}/SuperGen.h.dvi \
          ${DOC}/Whitehead.h.dvi

all: ${FILES} ${DOCFILES}
	@echo 44 finished ${IN}

${OUT}/AmalgamatedProductParser.h: ${IN}/AmalgamatedProductParser.h.pamphlet
	@echo 1 making ${OUT}/AmalgamatedProductParser.h from ${IN}/AmalgamatedProductParser.h.pamphlet
	@${DOCUMENT} src AmalgamatedProductParser.h ${OUT}

${DOC}/AmalgamatedProductParser.h.dvi: ${IN}/AmalgamatedProductParser.h.pamphlet ${DOC}/axiom.sty
	@echo 2 making ${DOC}/AmalgamatedProductParser.h.dvi from ${IN}/AmalgamatedProductParser.h.pamphlet 
	@${DOCUMENT} dvi AmalgamatedProductParser.h ${DOC} AmalgamatedProductParser.h ${NOISE}


${OUT}/AP-fixups.h: ${IN}/AP-fixups.h.pamphlet
	@echo 3 making ${OUT}/AP-fixups.h from ${IN}/AP-fixups.h.pamphlet
	@${DOCUMENT} src AP-fixups.h ${OUT}

${DOC}/AP-fixups.h.dvi: ${IN}/AP-fixups.h.pamphlet ${DOC}/axiom.sty
	@echo 42 making ${DOC}/AP-fixups.h.dvi from ${IN}/AP-fixups.h.pamphlet 
	@${DOCUMENT} dvi AP-fixups.h ${DOC} AP-fixups.h ${NOISE}


${OUT}/APofFreeGroups.h: ${IN}/APofFreeGroups.h.pamphlet
	@echo 5 making ${OUT}/APofFreeGroups.h from ${IN}/APofFreeGroups.h.pamphlet
	@${DOCUMENT} src APofFreeGroups.h ${OUT}

${DOC}/APofFreeGroups.h.dvi: ${IN}/APofFreeGroups.h.pamphlet ${DOC}/axiom.sty
	@echo 6 making ${DOC}/APofFreeGroups.h.dvi from ${IN}/APofFreeGroups.h.pamphlet 
	@${DOCUMENT} dvi APofFreeGroups.h ${DOC} APofFreeGroups.h ${NOISE}


${OUT}/APofFreeGroupsRep.h: ${IN}/APofFreeGroupsRep.h.pamphlet
	@echo 7 making ${OUT}/APofFreeGroupsRep.h from ${IN}/APofFreeGroupsRep.h.pamphlet
	@${DOCUMENT} src APofFreeGroupsRep.h ${OUT}

${DOC}/APofFreeGroupsRep.h.dvi: ${IN}/APofFreeGroupsRep.h.pamphlet ${DOC}/axiom.sty
	@echo 8 making ${DOC}/APofFreeGroupsRep.h.dvi from ${IN}/APofFreeGroupsRep.h.pamphlet 
	@${DOCUMENT} dvi APofFreeGroupsRep.h ${DOC} APofFreeGroupsRep.h ${NOISE}


${OUT}/APwithOneRelator.h: ${IN}/APwithOneRelator.h.pamphlet
	@echo 9 making ${OUT}/APwithOneRelator.h from ${IN}/APwithOneRelator.h.pamphlet
	@${DOCUMENT} src APwithOneRelator.h ${OUT}

${DOC}/APwithOneRelator.h.dvi: ${IN}/APwithOneRelator.h.pamphlet ${DOC}/axiom.sty
	@echo 10 making ${DOC}/APwithOneRelator.h.dvi from ${IN}/APwithOneRelator.h.pamphlet 
	@${DOCUMENT} dvi APwithOneRelator.h ${DOC} APwithOneRelator.h ${NOISE}


${OUT}/APwithOneRelatorRep.h: ${IN}/APwithOneRelatorRep.h.pamphlet
	@echo 11 making ${OUT}/APwithOneRelatorRep.h from ${IN}/APwithOneRelatorRep.h.pamphlet
	@${DOCUMENT} src APwithOneRelatorRep.h ${OUT}

${DOC}/APwithOneRelatorRep.h.dvi: ${IN}/APwithOneRelatorRep.h.pamphlet ${DOC}/axiom.sty
	@echo 12 making ${DOC}/APwithOneRelatorRep.h.dvi from ${IN}/APwithOneRelatorRep.h.pamphlet 
	@${DOCUMENT} dvi APwithOneRelatorRep.h ${DOC} APwithOneRelatorRep.h ${NOISE}


${OUT}/CONDITION.h: ${IN}/CONDITION.h.pamphlet
	@echo 13 making ${OUT}/CONDITION.h from ${IN}/CONDITION.h.pamphlet
	@${DOCUMENT} src CONDITION.h ${OUT}

${DOC}/CONDITION.h.dvi: ${IN}/CONDITION.h.pamphlet ${DOC}/axiom.sty
	@echo 14 making ${DOC}/CONDITION.h.dvi from ${IN}/CONDITION.h.pamphlet 
	@${DOCUMENT} dvi CONDITION.h ${DOC} CONDITION.h ${NOISE}


${OUT}/HNNExtension.h: ${IN}/HNNExtension.h.pamphlet
	@echo 15 making ${OUT}/HNNExtension.h from ${IN}/HNNExtension.h.pamphlet
	@${DOCUMENT} src HNNExtension.h ${OUT}

${DOC}/HNNExtension.h.dvi: ${IN}/HNNExtension.h.pamphlet ${DOC}/axiom.sty
	@echo 16 making ${DOC}/HNNExtension.h.dvi from ${IN}/HNNExtension.h.pamphlet 
	@${DOCUMENT} dvi HNNExtension.h ${DOC} HNNExtension.h ${NOISE}


${OUT}/HNNExtOfFreeGroup.h: ${IN}/HNNExtOfFreeGroup.h.pamphlet
	@echo 17 making ${OUT}/HNNExtOfFreeGroup.h from ${IN}/HNNExtOfFreeGroup.h.pamphlet
	@${DOCUMENT} src HNNExtOfFreeGroup.h ${OUT}

${DOC}/HNNExtOfFreeGroup.h.dvi: ${IN}/HNNExtOfFreeGroup.h.pamphlet ${DOC}/axiom.sty
	@echo 18 making ${DOC}/HNNExtOfFreeGroup.h.dvi from ${IN}/HNNExtOfFreeGroup.h.pamphlet 
	@${DOCUMENT} dvi HNNExtOfFreeGroup.h ${DOC} HNNExtOfFreeGroup.h ${NOISE}


${OUT}/HNNExtOfORGroup.h: ${IN}/HNNExtOfORGroup.h.pamphlet
	@echo 19 making ${OUT}/HNNExtOfORGroup.h from ${IN}/HNNExtOfORGroup.h.pamphlet
	@${DOCUMENT} src HNNExtOfORGroup.h ${OUT}

${DOC}/HNNExtOfORGroup.h.dvi: ${IN}/HNNExtOfORGroup.h.pamphlet ${DOC}/axiom.sty
	@echo 20 making ${DOC}/HNNExtOfORGroup.h.dvi from ${IN}/HNNExtOfORGroup.h.pamphlet 
	@${DOCUMENT} dvi HNNExtOfORGroup.h ${DOC} HNNExtOfORGroup.h ${NOISE}


${OUT}/HNNParser.h: ${IN}/HNNParser.h.pamphlet
	@echo 21 making ${OUT}/HNNParser.h from ${IN}/HNNParser.h.pamphlet
	@${DOCUMENT} src HNNParser.h ${OUT}

${DOC}/HNNParser.h.dvi: ${IN}/HNNParser.h.pamphlet ${DOC}/axiom.sty
	@echo 22 making ${DOC}/HNNParser.h.dvi from ${IN}/HNNParser.h.pamphlet 
	@${DOCUMENT} dvi HNNParser.h ${DOC} HNNParser.h ${NOISE}


${OUT}/MagnusBreakdown.h: ${IN}/MagnusBreakdown.h.pamphlet
	@echo 23 making ${OUT}/MagnusBreakdown.h from ${IN}/MagnusBreakdown.h.pamphlet
	@${DOCUMENT} src MagnusBreakdown.h ${OUT}

${DOC}/MagnusBreakdown.h.dvi: ${IN}/MagnusBreakdown.h.pamphlet ${DOC}/axiom.sty
	@echo 24 making ${DOC}/MagnusBreakdown.h.dvi from ${IN}/MagnusBreakdown.h.pamphlet 
	@${DOCUMENT} dvi MagnusBreakdown.h ${DOC} MagnusBreakdown.h ${NOISE}


${OUT}/Margin.h: ${IN}/Margin.h.pamphlet
	@echo 25 making ${OUT}/Margin.h from ${IN}/Margin.h.pamphlet
	@${DOCUMENT} src Margin.h ${OUT}

${DOC}/Margin.h.dvi: ${IN}/Margin.h.pamphlet ${DOC}/axiom.sty
	@echo 26 making ${DOC}/Margin.h.dvi from ${IN}/Margin.h.pamphlet 
	@${DOCUMENT} dvi Margin.h ${DOC} Margin.h ${NOISE}


${OUT}/OneRelatorGroup.h: ${IN}/OneRelatorGroup.h.pamphlet
	@echo 27 making ${OUT}/OneRelatorGroup.h from ${IN}/OneRelatorGroup.h.pamphlet
	@${DOCUMENT} src OneRelatorGroup.h ${OUT}

${DOC}/OneRelatorGroup.h.dvi: ${IN}/OneRelatorGroup.h.pamphlet ${DOC}/axiom.sty
	@echo 28 making ${DOC}/OneRelatorGroup.h.dvi from ${IN}/OneRelatorGroup.h.pamphlet 
	@${DOCUMENT} dvi OneRelatorGroup.h ${DOC} OneRelatorGroup.h ${NOISE}


${OUT}/OneRelatorGroupWithTorsion.h: ${IN}/OneRelatorGroupWithTorsion.h.pamphlet
	@echo 29 making ${OUT}/OneRelatorGroupWithTorsion.h from ${IN}/OneRelatorGroupWithTorsion.h.pamphlet
	@${DOCUMENT} src OneRelatorGroupWithTorsion.h ${OUT}

${DOC}/OneRelatorGroupWithTorsion.h.dvi: ${IN}/OneRelatorGroupWithTorsion.h.pamphlet ${DOC}/axiom.sty
	@echo 30 making ${DOC}/OneRelatorGroupWithTorsion.h.dvi from ${IN}/OneRelatorGroupWithTorsion.h.pamphlet 
	@${DOCUMENT} dvi OneRelatorGroupWithTorsion.h ${DOC} OneRelatorGroupWithTorsion.h ${NOISE}


${OUT}/ORProblems.h: ${IN}/ORProblems.h.pamphlet
	@echo 31 making ${OUT}/ORProblems.h from ${IN}/ORProblems.h.pamphlet
	@${DOCUMENT} src ORProblems.h ${OUT}

${DOC}/ORProblems.h.dvi: ${IN}/ORProblems.h.pamphlet ${DOC}/axiom.sty
	@echo 32 making ${DOC}/ORProblems.h.dvi from ${IN}/ORProblems.h.pamphlet 
	@${DOCUMENT} dvi ORProblems.h ${DOC} ORProblems.h ${NOISE}


${OUT}/Range.h: ${IN}/Range.h.pamphlet
	@echo 33 making ${OUT}/Range.h from ${IN}/Range.h.pamphlet
	@${DOCUMENT} src Range.h ${OUT}

${DOC}/Range.h.dvi: ${IN}/Range.h.pamphlet ${DOC}/axiom.sty
	@echo 34 making ${DOC}/Range.h.dvi from ${IN}/Range.h.pamphlet 
	@${DOCUMENT} dvi Range.h ${DOC} Range.h ${NOISE}


${OUT}/ShortenByRelators2.h: ${IN}/ShortenByRelators2.h.pamphlet
	@echo 35 making ${OUT}/ShortenByRelators2.h from ${IN}/ShortenByRelators2.h.pamphlet
	@${DOCUMENT} src ShortenByRelators2.h ${OUT}

${DOC}/ShortenByRelators2.h.dvi: ${IN}/ShortenByRelators2.h.pamphlet ${DOC}/axiom.sty
	@echo 36 making ${DOC}/ShortenByRelators2.h.dvi from ${IN}/ShortenByRelators2.h.pamphlet 
	@${DOCUMENT} dvi ShortenByRelators2.h ${DOC} ShortenByRelators2.h ${NOISE}


${OUT}/SubgroupOfOneRelatorGroup.h: ${IN}/SubgroupOfOneRelatorGroup.h.pamphlet
	@echo 37 making ${OUT}/SubgroupOfOneRelatorGroup.h from ${IN}/SubgroupOfOneRelatorGroup.h.pamphlet
	@${DOCUMENT} src SubgroupOfOneRelatorGroup.h ${OUT}

${DOC}/SubgroupOfOneRelatorGroup.h.dvi: ${IN}/SubgroupOfOneRelatorGroup.h.pamphlet ${DOC}/axiom.sty
	@echo 38 making ${DOC}/SubgroupOfOneRelatorGroup.h.dvi from ${IN}/SubgroupOfOneRelatorGroup.h.pamphlet 
	@${DOCUMENT} dvi SubgroupOfOneRelatorGroup.h ${DOC} SubgroupOfOneRelatorGroup.h ${NOISE}


${OUT}/SuperGen.h: ${IN}/SuperGen.h.pamphlet
	@echo 39 making ${OUT}/SuperGen.h from ${IN}/SuperGen.h.pamphlet
	@${DOCUMENT} src SuperGen.h ${OUT}

${DOC}/SuperGen.h.dvi: ${IN}/SuperGen.h.pamphlet ${DOC}/axiom.sty
	@echo 40 making ${DOC}/SuperGen.h.dvi from ${IN}/SuperGen.h.pamphlet 
	@${DOCUMENT} dvi SuperGen.h ${DOC} SuperGen.h ${NOISE}


${OUT}/Whitehead.h: ${IN}/Whitehead.h.pamphlet
	@echo 41 making ${OUT}/Whitehead.h from ${IN}/Whitehead.h.pamphlet
	@${DOCUMENT} src Whitehead.h ${OUT}

${DOC}/Whitehead.h.dvi: ${IN}/Whitehead.h.pamphlet ${DOC}/axiom.sty
	@echo 42 making ${DOC}/Whitehead.h.dvi from ${IN}/Whitehead.h.pamphlet 
	@${DOCUMENT} dvi Whitehead.h ${DOC} Whitehead.h ${NOISE}


${DOC}/axiom.sty: ${SRC}/doc/axiom.sty.pamphlet
	@ echo 43 making ${DOC}/axiom.sty from ${SRC}/doc/axiom.sty.pamphlet
	@${DOCUMENT} chunk "axiom.sty" ${SRC}/doc/axiom.sty ${DOC} axiom.sty
 
