#window box help file for abelian group check in

set helpStrings(abelGroupDialog) {

For example,

< s, t >

describes the free abelian group on s and t,

< x, y; x^2  y^3 > 

is the factor group of the free abelian group 
on x and y by the subgroup generated by x^2 y^3 
and

< b, t,u | b^2 t = b b b, b^-2 t^4 u^8 >

is the quotient of the free abelian group on b,t 
and u by the subgroup generated by b^2 t B B B 
and B B t^4 u^8. Notice that we use upper case 
letters in place of the inverses of the 
corresponding lower case letters - thus B =b^-1 
and so on.

In working with abelian groups we work in the 
category of abelian groups. Thus presentations 
of abelian groups are all relative to a free 
abelian group, which means adding commutators 
to a presentation is redundant. 

}


# window box help file for permutation group check in

set helpStrings(pmgpFormatDialog) {
Example:
    gp( (1,2), (3,4,5)*(2,3))

   Every finite permutation group is a subgroup of a symmetric group on n symbols for some n. No relators need to be entered, only generators, since the group being checked in is a subgroup of an already existing group.

  The example above is the subgroup of S_5 generated by the cycle (1 2) and (3 4 5)(2 3). 

}

