IN=${SRC}/backend/NilpotentGroup/include
OUT=${INT}/include
DOC=${MNT}/${SYS}/doc/src/backend/NilpotentGroup/include


FILES= ${OUT}/BasicCommutators.h ${OUT}/FPNilpotentGroupRep.h \
       ${OUT}/FreeNilpotentGroupRep.h ${OUT}/LCSQuotients.h \
       ${OUT}/Letter.h ${OUT}/MalcevSet.h \
       ${OUT}/NilpCollectors.h ${OUT}/NilpotentCollector.h \
       ${OUT}/NilpotentGroup.h ${OUT}/NilpotentGroupRep.h \
       ${OUT}/PolyWord.h ${OUT}/PolyWordIterator.h \
       ${OUT}/PolyWordRep.h ${OUT}/Presentation.h \
       ${OUT}/SGOfFNGRep.h ${OUT}/SGOfFPNGRep.h \
       ${OUT}/SGOfNilpotentGroup.h ${OUT}/SGOfNilpotentGroupRep.h \
       ${OUT}/SubgroupBasis.h

DOCFILES= ${DOC}/BasicCommutators.h.dvi ${DOC}/FPNilpotentGroupRep.h.dvi \
          ${DOC}/FreeNilpotentGroupRep.h.dvi ${DOC}/LCSQuotients.h.dvi \
          ${DOC}/Letter.h.dvi ${DOC}/MalcevSet.h.dvi \
          ${DOC}/NilpCollectors.h.dvi ${DOC}/NilpotentCollector.h.dvi \
          ${DOC}/NilpotentGroup.h.dvi ${DOC}/NilpotentGroupRep.h.dvi \
          ${DOC}/PolyWord.h.dvi ${DOC}/PolyWordIterator.h.dvi \
          ${DOC}/PolyWordRep.h.dvi ${DOC}/Presentation.h.dvi \
          ${DOC}/SGOfFNGRep.h.dvi ${DOC}/SGOfFPNGRep.h.dvi \
          ${DOC}/SGOfNilpotentGroup.h.dvi ${DOC}/SGOfNilpotentGroupRep.h.dvi \
          ${DOC}/SubgroupBasis.h.dvi

all: ${FILES} ${DOCFILES}
	@echo 40 finished ${IN}

${OUT}/BasicCommutators.h: ${IN}/BasicCommutators.h.pamphlet
	@echo 1 making ${OUT}/BasicCommutators.h from ${IN}/BasicCommutators.h.pamphlet
	@${DOCUMENT} src BasicCommutators.h ${OUT}

${DOC}/BasicCommutators.h.dvi: ${IN}/BasicCommutators.h.pamphlet ${DOC}/axiom.sty
	@echo 2 making ${DOC}/BasicCommutators.h.dvi from ${IN}/BasicCommutators.h.pamphlet 
	@${DOCUMENT} dvi BasicCommutators.h ${DOC} BasicCommutators.h ${NOISE}


${OUT}/FPNilpotentGroupRep.h: ${IN}/FPNilpotentGroupRep.h.pamphlet
	@echo 3 making ${OUT}/FPNilpotentGroupRep.h from ${IN}/FPNilpotentGroupRep.h.pamphlet
	@${DOCUMENT} src FPNilpotentGroupRep.h ${OUT}

${DOC}/FPNilpotentGroupRep.h.dvi: ${IN}/FPNilpotentGroupRep.h.pamphlet ${DOC}/axiom.sty
	@echo 4 making ${DOC}/FPNilpotentGroupRep.h.dvi from ${IN}/FPNilpotentGroupRep.h.pamphlet 
	@${DOCUMENT} dvi FPNilpotentGroupRep.h ${DOC} FPNilpotentGroupRep.h ${NOISE}


${OUT}/FreeNilpotentGroupRep.h: ${IN}/FreeNilpotentGroupRep.h.pamphlet
	@echo 5 making ${OUT}/FreeNilpotentGroupRep.h from ${IN}/FreeNilpotentGroupRep.h.pamphlet
	@${DOCUMENT} src FreeNilpotentGroupRep.h ${OUT}

${DOC}/FreeNilpotentGroupRep.h.dvi: ${IN}/FreeNilpotentGroupRep.h.pamphlet ${DOC}/axiom.sty
	@echo 6 making ${DOC}/FreeNilpotentGroupRep.h.dvi from ${IN}/FreeNilpotentGroupRep.h.pamphlet 
	@${DOCUMENT} dvi FreeNilpotentGroupRep.h ${DOC} FreeNilpotentGroupRep.h ${NOISE}


${OUT}/LCSQuotients.h: ${IN}/LCSQuotients.h.pamphlet
	@echo 7 making ${OUT}/LCSQuotients.h from ${IN}/LCSQuotients.h.pamphlet
	@${DOCUMENT} src LCSQuotients.h ${OUT}

${DOC}/LCSQuotients.h.dvi: ${IN}/LCSQuotients.h.pamphlet ${DOC}/axiom.sty
	@echo 8 making ${DOC}/LCSQuotients.h.dvi from ${IN}/LCSQuotients.h.pamphlet 
	@${DOCUMENT} dvi LCSQuotients.h ${DOC} LCSQuotients.h ${NOISE}


${OUT}/Letter.h: ${IN}/Letter.h.pamphlet
	@echo 9 making ${OUT}/Letter.h from ${IN}/Letter.h.pamphlet
	@${DOCUMENT} src Letter.h ${OUT}

${DOC}/Letter.h.dvi: ${IN}/Letter.h.pamphlet ${DOC}/axiom.sty
	@echo 10 making ${DOC}/Letter.h.dvi from ${IN}/Letter.h.pamphlet 
	@${DOCUMENT} dvi Letter.h ${DOC} Letter.h ${NOISE}


${OUT}/MalcevSet.h: ${IN}/MalcevSet.h.pamphlet
	@echo 11 making ${OUT}/MalcevSet.h from ${IN}/MalcevSet.h.pamphlet
	@${DOCUMENT} src MalcevSet.h ${OUT}

${DOC}/MalcevSet.h.dvi: ${IN}/MalcevSet.h.pamphlet ${DOC}/axiom.sty
	@echo 12 making ${DOC}/MalcevSet.h.dvi from ${IN}/MalcevSet.h.pamphlet 
	@${DOCUMENT} dvi MalcevSet.h ${DOC} MalcevSet.h ${NOISE}


${OUT}/NilpCollectors.h: ${IN}/NilpCollectors.h.pamphlet
	@echo 13 making ${OUT}/NilpCollectors.h from ${IN}/NilpCollectors.h.pamphlet
	@${DOCUMENT} src NilpCollectors.h ${OUT}

${DOC}/NilpCollectors.h.dvi: ${IN}/NilpCollectors.h.pamphlet ${DOC}/axiom.sty
	@echo 14 making ${DOC}/NilpCollectors.h.dvi from ${IN}/NilpCollectors.h.pamphlet 
	@${DOCUMENT} dvi NilpCollectors.h ${DOC} NilpCollectors.h ${NOISE}


${OUT}/NilpotentCollector.h: ${IN}/NilpotentCollector.h.pamphlet
	@echo 15 making ${OUT}/NilpotentCollector.h from ${IN}/NilpotentCollector.h.pamphlet
	@${DOCUMENT} src NilpotentCollector.h ${OUT}

${DOC}/NilpotentCollector.h.dvi: ${IN}/NilpotentCollector.h.pamphlet ${DOC}/axiom.sty
	@echo 16 making ${DOC}/NilpotentCollector.h.dvi from ${IN}/NilpotentCollector.h.pamphlet 
	@${DOCUMENT} dvi NilpotentCollector.h ${DOC} NilpotentCollector.h ${NOISE}


${OUT}/NilpotentGroup.h: ${IN}/NilpotentGroup.h.pamphlet
	@echo 17 making ${OUT}/NilpotentGroup.h from ${IN}/NilpotentGroup.h.pamphlet
	@${DOCUMENT} src NilpotentGroup.h ${OUT}

${DOC}/NilpotentGroup.h.dvi: ${IN}/NilpotentGroup.h.pamphlet ${DOC}/axiom.sty
	@echo 18 making ${DOC}/NilpotentGroup.h.dvi from ${IN}/NilpotentGroup.h.pamphlet 
	@${DOCUMENT} dvi NilpotentGroup.h ${DOC} NilpotentGroup.h ${NOISE}


${OUT}/NilpotentGroupRep.h: ${IN}/NilpotentGroupRep.h.pamphlet
	@echo 19 making ${OUT}/NilpotentGroupRep.h from ${IN}/NilpotentGroupRep.h.pamphlet
	@${DOCUMENT} src NilpotentGroupRep.h ${OUT}

${DOC}/NilpotentGroupRep.h.dvi: ${IN}/NilpotentGroupRep.h.pamphlet ${DOC}/axiom.sty
	@echo 20 making ${DOC}/NilpotentGroupRep.h.dvi from ${IN}/NilpotentGroupRep.h.pamphlet 
	@${DOCUMENT} dvi NilpotentGroupRep.h ${DOC} NilpotentGroupRep.h ${NOISE}


${OUT}/PolyWord.h: ${IN}/PolyWord.h.pamphlet
	@echo 21 making ${OUT}/PolyWord.h from ${IN}/PolyWord.h.pamphlet
	@${DOCUMENT} src PolyWord.h ${OUT}

${DOC}/PolyWord.h.dvi: ${IN}/PolyWord.h.pamphlet ${DOC}/axiom.sty
	@echo 22 making ${DOC}/PolyWord.h.dvi from ${IN}/PolyWord.h.pamphlet 
	@${DOCUMENT} dvi PolyWord.h ${DOC} PolyWord.h ${NOISE}


${OUT}/PolyWordIterator.h: ${IN}/PolyWordIterator.h.pamphlet
	@echo 23 making ${OUT}/PolyWordIterator.h from ${IN}/PolyWordIterator.h.pamphlet
	@${DOCUMENT} src PolyWordIterator.h ${OUT}

${DOC}/PolyWordIterator.h.dvi: ${IN}/PolyWordIterator.h.pamphlet ${DOC}/axiom.sty
	@echo 24 making ${DOC}/PolyWordIterator.h.dvi from ${IN}/PolyWordIterator.h.pamphlet 
	@${DOCUMENT} dvi PolyWordIterator.h ${DOC} PolyWordIterator.h ${NOISE}


${OUT}/PolyWordRep.h: ${IN}/PolyWordRep.h.pamphlet
	@echo 25 making ${OUT}/PolyWordRep.h from ${IN}/PolyWordRep.h.pamphlet
	@${DOCUMENT} src PolyWordRep.h ${OUT}

${DOC}/PolyWordRep.h.dvi: ${IN}/PolyWordRep.h.pamphlet ${DOC}/axiom.sty
	@echo 26 making ${DOC}/PolyWordRep.h.dvi from ${IN}/PolyWordRep.h.pamphlet 
	@${DOCUMENT} dvi PolyWordRep.h ${DOC} PolyWordRep.h ${NOISE}


${OUT}/Presentation.h: ${IN}/Presentation.h.pamphlet
	@echo 27 making ${OUT}/Presentation.h from ${IN}/Presentation.h.pamphlet
	@${DOCUMENT} src Presentation.h ${OUT}

${DOC}/Presentation.h.dvi: ${IN}/Presentation.h.pamphlet ${DOC}/axiom.sty
	@echo 28 making ${DOC}/Presentation.h.dvi from ${IN}/Presentation.h.pamphlet 
	@${DOCUMENT} dvi Presentation.h ${DOC} Presentation.h ${NOISE}


${OUT}/SGOfFNGRep.h: ${IN}/SGOfFNGRep.h.pamphlet
	@echo 29 making ${OUT}/SGOfFNGRep.h from ${IN}/SGOfFNGRep.h.pamphlet
	@${DOCUMENT} src SGOfFNGRep.h ${OUT}

${DOC}/SGOfFNGRep.h.dvi: ${IN}/SGOfFNGRep.h.pamphlet ${DOC}/axiom.sty
	@echo 30 making ${DOC}/SGOfFNGRep.h.dvi from ${IN}/SGOfFNGRep.h.pamphlet 
	@${DOCUMENT} dvi SGOfFNGRep.h ${DOC} SGOfFNGRep.h ${NOISE}


${OUT}/SGOfFPNGRep.h: ${IN}/SGOfFPNGRep.h.pamphlet
	@echo 31 making ${OUT}/SGOfFPNGRep.h from ${IN}/SGOfFPNGRep.h.pamphlet
	@${DOCUMENT} src SGOfFPNGRep.h ${OUT}

${DOC}/SGOfFPNGRep.h.dvi: ${IN}/SGOfFPNGRep.h.pamphlet ${DOC}/axiom.sty
	@echo 32 making ${DOC}/SGOfFPNGRep.h.dvi from ${IN}/SGOfFPNGRep.h.pamphlet 
	@${DOCUMENT} dvi SGOfFPNGRep.h ${DOC} SGOfFPNGRep.h ${NOISE}


${OUT}/SGOfNilpotentGroup.h: ${IN}/SGOfNilpotentGroup.h.pamphlet
	@echo 33 making ${OUT}/SGOfNilpotentGroup.h from ${IN}/SGOfNilpotentGroup.h.pamphlet
	@${DOCUMENT} src SGOfNilpotentGroup.h ${OUT}

${DOC}/SGOfNilpotentGroup.h.dvi: ${IN}/SGOfNilpotentGroup.h.pamphlet ${DOC}/axiom.sty
	@echo 34 making ${DOC}/SGOfNilpotentGroup.h.dvi from ${IN}/SGOfNilpotentGroup.h.pamphlet 
	@${DOCUMENT} dvi SGOfNilpotentGroup.h ${DOC} SGOfNilpotentGroup.h ${NOISE}


${OUT}/SGOfNilpotentGroupRep.h: ${IN}/SGOfNilpotentGroupRep.h.pamphlet
	@echo 35 making ${OUT}/SGOfNilpotentGroupRep.h from ${IN}/SGOfNilpotentGroupRep.h.pamphlet
	@${DOCUMENT} src SGOfNilpotentGroupRep.h ${OUT}

${DOC}/SGOfNilpotentGroupRep.h.dvi: ${IN}/SGOfNilpotentGroupRep.h.pamphlet ${DOC}/axiom.sty
	@echo 36 making ${DOC}/SGOfNilpotentGroupRep.h.dvi from ${IN}/SGOfNilpotentGroupRep.h.pamphlet 
	@${DOCUMENT} dvi SGOfNilpotentGroupRep.h ${DOC} SGOfNilpotentGroupRep.h ${NOISE}


${OUT}/SubgroupBasis.h: ${IN}/SubgroupBasis.h.pamphlet
	@echo 37 making ${OUT}/SubgroupBasis.h from ${IN}/SubgroupBasis.h.pamphlet
	@${DOCUMENT} src SubgroupBasis.h ${OUT}

${DOC}/SubgroupBasis.h.dvi: ${IN}/SubgroupBasis.h.pamphlet ${DOC}/axiom.sty
	@echo 38 making ${DOC}/SubgroupBasis.h.dvi from ${IN}/SubgroupBasis.h.pamphlet 
	@${DOCUMENT} dvi SubgroupBasis.h ${DOC} SubgroupBasis.h ${NOISE}


${DOC}/axiom.sty: ${SRC}/doc/axiom.sty.pamphlet
	@ echo 39 making ${DOC}/axiom.sty from ${SRC}/doc/axiom.sty.pamphlet
	@${DOCUMENT} chunk "axiom.sty" ${SRC}/doc/axiom.sty ${DOC} axiom.sty
 
